import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ShoppingBag,Heart,User,MapPin,Menu,X,ChevronRight,Truck,ShieldCheck,RefreshCw,Plus,Minus,Star,Package,Instagram,Mail} from 'lucide-react';
import './styles.css';

const regions=['Rajasthan','Gujarat','Madhya Pradesh','Karnataka','West Bengal','Bihar','Assam','Odisha','Uttar Pradesh','Tamil Nadu'];
const categories=['Handicrafts','Textiles','Home & Living','Jewellery','Food & Spices','Gifts'];
const products=[
['RJ-001','Blue Pottery Serving Bowl','Rajasthan','Handicrafts',899,'Hand-painted Jaipur blue pottery bowl inspired by traditional Rajasthani motifs.','Artisan-made · Food-safe finish'],
['RJ-002','Bandhani Dupatta','Rajasthan','Textiles',1299,'A vibrant tie-dyed Bandhani dupatta made with traditional craft techniques.','Handcrafted · Lightweight cotton-silk'],
['RJ-003','Kundan Heritage Earrings','Rajasthan','Jewellery',1499,'Festive Kundan-inspired earrings with a detailed heritage finish.','Gift-ready · Nickel-conscious base'],
['GJ-001','Ajrakh Cotton Stole','Gujarat','Textiles',1199,'Block-printed cotton stole featuring classic Ajrakh-inspired geometry.','Natural-look print · Soft cotton'],
['GJ-002','Gujarati Wood Craft Box','Gujarat','Home & Living',749,'Decorative wooden keepsake box for jewellery, notes and gifts.','Hand-finished · Compact'],
['GJ-003','Kutchi Embroidery Cushion','Gujarat','Home & Living',999,'Colourful Kutchi-inspired embroidered cushion cover for a warm home.','18×18 in · Cover only'],
['MP-001','Chanderi Silk-Cotton Saree','Madhya Pradesh','Textiles',2499,'Elegant Chanderi-inspired weave with a light drape for festive occasions.','Handloom-inspired · Gift wrap available'],
['MP-002','Gond Art Print','Madhya Pradesh','Gifts',699,'Decorative print inspired by the storytelling traditions of Gond art.','A4 · Unframed'],
['MP-003','Terracotta Diya Set','Madhya Pradesh','Home & Living',449,'Set of traditional terracotta diyas for festive home décor.','Set of 8 · Reusable'],
['KA-001','Mysore Sandal Soap Gift Box','Karnataka','Gifts',599,'A curated bath gift box inspired by Karnataka sandalwood heritage.','Gift-ready packaging'],
['KA-002','Ilkal Cotton Saree','Karnataka','Textiles',2199,'Traditional-looking cotton saree with a bold regional border.','Breathable · Everyday festive'],
['KA-003','Channapatna Toy Pair','Karnataka','Gifts',799,'Colourful turned-wood decorative toys inspired by Channapatna craft.','Non-toxic lacquer look'],
['WB-001','Kantha Embroidered Tote','West Bengal','Textiles',1099,'Everyday tote featuring Kantha-inspired running-stitch embroidery.','Cotton · Inner pocket'],
['WB-002','Terracotta Horse Décor','West Bengal','Home & Living',899,'A sculptural terracotta horse inspired by Bankura craft traditions.','Hand-finished · Display piece'],
['WB-003','Darjeeling Tea Gift Tin','West Bengal','Food & Spices',649,'A premium tea gift tin curated around Darjeeling tea culture.','100g · Gift-ready'],
['BR-001','Madhubani Art Print','Bihar','Gifts',699,'Colour-rich print inspired by the storytelling vocabulary of Madhubani art.','A4 · Unframed'],
['BR-002','Sikki Grass Basket','Bihar','Home & Living',799,'Handwoven basket inspired by Bihar’s Sikki craft tradition.','Natural fibre · Storage'],
['BR-003','Makhana Snack Box','Bihar','Food & Spices',499,'Roasted makhana gift box for light snacking and gifting.','250g · Packed for freshness'],
['AS-001','Muga-inspired Silk Stole','Assam','Textiles',1799,'A refined stole inspired by Assam’s silk weaving heritage.','Soft drape · Occasion wear'],
['AS-002','Assam Tea Breakfast Box','Assam','Food & Spices',699,'Breakfast tea assortment curated around Assam tea culture.','200g · Gift-ready'],
['AS-003','Bamboo Utility Basket','Assam','Home & Living',649,'Lightweight bamboo basket for desk, kitchen or living spaces.','Natural finish'],
['OD-001','Pattachitra Art Print','Odisha','Gifts',799,'Decorative artwork inspired by Odisha’s detailed Pattachitra tradition.','A4 · Unframed'],
['OD-002','Silver Filigree-inspired Pendant','Odisha','Jewellery',1399,'Fine-looking pendant inspired by Odisha’s intricate filigree vocabulary.','Gift pouch included'],
['OD-003','Stone Carving Décor','Odisha','Home & Living',999,'Small display sculpture inspired by Odisha’s stone-carving heritage.','Hand-finished'],
['UP-001','Banarasi Silk Stole','Uttar Pradesh','Textiles',1999,'Festive stole inspired by the rich weaving tradition of Varanasi.','Lightweight · Occasion wear'],
['UP-002','Moradabad Metal Tray','Uttar Pradesh','Home & Living',899,'Decorative metal tray inspired by Moradabad’s metal craft tradition.','Display use · Wipe clean'],
['UP-003','Brass Diya Pair','Uttar Pradesh','Home & Living',549,'Classic brass-look diyas for festive décor and gifting.','Pair · Gift box'],
['TN-001','Kanjivaram-inspired Silk Scarf','Tamil Nadu','Textiles',1599,'Richly coloured scarf inspired by Tamil Nadu’s silk weaving heritage.','Soft finish · Gift-ready'],
['TN-002','Tanjore Art Print','Tamil Nadu','Gifts',799,'Decorative print inspired by the ornate visual language of Tanjore art.','A4 · Unframed'],
['TN-003','Bronze-style Nataraja Décor','Tamil Nadu','Home & Living',1299,'A compact décor piece inspired by South Indian bronze sculpture forms.','Display piece · 8 in']
].map(([sku,name,region,category,price,desc,details],i)=>({sku,name,region,category,price,desc,details,id:i+1,stock:'In stock',rating:(4.5+(i%5)*.1).toFixed(1),image:`/products/${sku}.svg`}));

const money=n=>'₹'+n.toLocaleString('en-IN');
function ProductArt({p}){return <div className="product-art"><div className="art-region">{p.region}</div><div className="art-shape"><span>{p.category==='Textiles'?'✦':p.category==='Jewellery'?'◇':p.category==='Food & Spices'?'✿':p.category==='Gifts'?'◈':'❋'}</span></div><div className="art-caption">FREEMART • {p.sku}</div></div>}

function App(){
 const [page,setPage]=useState('home'),[menu,setMenu]=useState(false),[search,setSearch]=useState(''),[region,setRegion]=useState('All'),[category,setCategory]=useState('All'),[sort,setSort]=useState('featured'),[cart,setCart]=useState([]),[wishlist,setWishlist]=useState([]),[selected,setSelected]=useState(null),[toast,setToast]=useState('');
 const [orders,setOrders]=useState([]);
 const filtered=useMemo(()=>{let a=products.filter(p=>(region==='All'||p.region===region)&&(category==='All'||p.category===category)&&(p.name+' '+p.region+' '+p.category).toLowerCase().includes(search.toLowerCase())); if(sort==='priceLow')a.sort((x,y)=>x.price-y.price);if(sort==='priceHigh')a.sort((x,y)=>y.price-x.price);return a},[region,category,search,sort]);
 const count=cart.reduce((s,x)=>s+x.qty,0),subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const add=p=>{setCart(c=>{let old=c.find(x=>x.sku===p.sku);return old?c.map(x=>x.sku===p.sku?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});notify('Added to cart');};
 const nav=p=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});};
 const toggleWish=p=>{setWishlist(w=>w.includes(p.sku)?w.filter(x=>x!==p.sku):[...w,p.sku]);notify(wishlist.includes(p.sku)?'Removed from wishlist':'Saved to wishlist')};
 return <div className="app">
  <div className="topbar">Free delivery on orders above ₹1,999 <span>•</span> Authentic regional stories, thoughtfully curated</div>
  <header><div className="navwrap"><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><button className="brand" onClick={()=>nav('home')}><span>FM</span><div><b>FreeMart</b><small>SHOP INDIA BY REGION</small></div></button><nav className={menu?'open':''}><button onClick={()=>nav('home')}>Home</button><button onClick={()=>nav('shop')}>Shop</button><button onClick={()=>nav('regions')}>Regions</button><button onClick={()=>nav('categories')}>Categories</button><button onClick={()=>nav('gifts')}>Gift Collections</button><button onClick={()=>nav('about')}>Our Story</button></nav><div className="actions"><div className="search"><Search size={18}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage('shop')}} placeholder="Search products..."/></div><button className="icon" onClick={()=>nav('wishlist')}><Heart/><em>{wishlist.length}</em></button><button className="icon" onClick={()=>nav('account')}><User/></button><button className="icon bag" onClick={()=>nav('cart')}><ShoppingBag/><em>{count}</em></button></div></div></header>
  {page==='home'&&<Home nav={nav} add={add} toggleWish={toggleWish} wishlist={wishlist} open={p=>{setSelected(p);setPage('product')}}/>} 
  {page==='shop'&&<Shop products={filtered} region={region} setRegion={setRegion} category={category} setCategory={setCategory} sort={sort} setSort={setSort} add={add} toggleWish={toggleWish} wishlist={wishlist} open={p=>{setSelected(p);setPage('product')}}/>}
  {page==='regions'&&<Regions nav={nav} setRegion={setRegion}/>} 
  {page==='categories'&&<Categories setCategory={setCategory} nav={nav}/>} 
  {page==='gifts'&&<Collection title="Gift Collections" intro="Thoughtful gifts with a story from across India." products={products.filter(p=>p.category==='Gifts'||p.price<900)} add={add} toggleWish={toggleWish} wishlist={wishlist} open={p=>{setSelected(p);setPage('product')}}/>}
  {page==='product'&&selected&&<ProductDetail p={selected} add={add} toggleWish={toggleWish} wished={wishlist.includes(selected.sku)} nav={nav}/>} 
  {page==='cart'&&<Cart cart={cart} setCart={setCart} subtotal={subtotal} nav={nav}/>} 
  {page==='checkout'&&<Checkout cart={cart} subtotal={subtotal} setOrders={setOrders} orders={orders} nav={nav} notify={notify}/>} 
  {page==='account'&&<Account orders={orders} nav={nav}/>} 
  {page==='wishlist'&&<Collection title="Your Wishlist" intro="Save regional finds for later." products={products.filter(p=>wishlist.includes(p.sku))} add={add} toggleWish={toggleWish} wishlist={wishlist} open={p=>{setSelected(p);setPage('product')}} empty="Your wishlist is waiting for a little discovery."/>}
  {page==='about'&&<About nav={nav}/>} 
  {page==='contact'&&<InfoPage title="Contact FreeMart" text="We’re building a thoughtful marketplace for regional Indian products. For launch enquiries, artisan partnerships and customer support, email hello@freemart.in."/>}
  {['faq','shipping','returns','privacy','terms'].includes(page)&&<InfoPage title={{faq:'FAQ',shipping:'Shipping Policy',returns:'Return & Refund Policy',privacy:'Privacy Policy',terms:'Terms & Conditions'}[page]} text="This page is a launch-ready placeholder. Final legal and operational wording should be reviewed and updated before the store goes live."/>}
  {page==='admin'&&<Admin products={products} orders={orders}/>} 
  <footer><div className="footergrid"><div><div className="brand foot"><span>FM</span><div><b>FreeMart</b><small>SHOP INDIA BY REGION</small></div></div><p>Discover regional craftsmanship, food and stories from across India — in one thoughtful marketplace.</p><div className="social"><Instagram/><span className="social-f">f</span><Mail/></div></div><div><h4>Explore</h4><button onClick={()=>nav('shop')}>Shop all</button><button onClick={()=>nav('regions')}>Shop by region</button><button onClick={()=>nav('gifts')}>Gift collections</button><button onClick={()=>nav('about')}>Our story</button></div><div><h4>Customer care</h4><button onClick={()=>nav('contact')}>Contact</button><button onClick={()=>nav('faq')}>FAQ</button><button onClick={()=>nav('shipping')}>Shipping</button><button onClick={()=>nav('returns')}>Returns</button></div><div><h4>Policies</h4><button onClick={()=>nav('privacy')}>Privacy</button><button onClick={()=>nav('terms')}>Terms</button><button onClick={()=>nav('account')}>My account</button></div></div><div className="copyright">© 2026 FreeMart.in · Built for India · Payment gateway can be connected after hosting setup</div></footer>
  {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}

function Home({nav,add,toggleWish,wishlist,open}){return <main><section className="hero"><div className="hero-copy"><span className="eyebrow">MADE IN INDIA · DISCOVERED BY REGION</span><h1>Every region has a story.<br/><i>Bring one home.</i></h1><p>Shop a growing collection of Indian crafts, textiles, food and gifts — connected to the places and people behind them.</p><div className="hero-buttons"><button className="primary" onClick={()=>nav('shop')}>Explore the collection <ChevronRight/></button><button className="secondary" onClick={()=>nav('regions')}>Shop by region</button></div></div><div className="hero-art"><div className="sun">INDIA</div><div className="mapwords">RAJASTHAN<br/>GUJARAT<br/>ASSAM<br/>ODISHA<br/>TAMIL NADU</div><div className="stamp">FREE<br/>MART<br/><small>IN</small></div></div></section><section className="trust"><div><Truck/> <b>Reliable delivery</b><span>Pan-India shipping</span></div><div><ShieldCheck/><b>Thoughtful sourcing</b><span>Regional stories first</span></div><div><RefreshCw/><b>Easy support</b><span>Customer-first help</span></div></section><section className="section"><div className="sectionhead"><div><span className="eyebrow">CURATED FOR YOU</span><h2>New & noteworthy</h2></div><button className="textbtn" onClick={()=>nav('shop')}>View all <ChevronRight/></button></div><div className="grid">{products.slice(0,8).map(p=><Card key={p.sku} p={p} add={add} toggleWish={toggleWish} wished={wishlist.includes(p.sku)} open={()=>open(p)} />)}</div></section><section className="regionband"><div><span className="eyebrow">TEN REGIONS. ONE MARKETPLACE.</span><h2>Start with a place you love.</h2><p>Explore regional craft traditions and discover something new.</p></div><div className="regionchips">{regions.map(r=><button key={r} onClick={()=>nav('regions')}>{r}</button>)}</div></section><section className="story"><div className="storyvisual"><div className="bigmark">भारत<br/><span>BHARAT</span></div></div><div><span className="eyebrow">THE FREEMART PROMISE</span><h2>Not just products.<br/>A sense of place.</h2><p>FreeMart brings together regional products with context — where it comes from, what makes it special, and the craft traditions that shaped it.</p><button className="primary" onClick={()=>nav('about')}>Read our story <ChevronRight/></button></div></section></main>}

function Card({p,add,toggleWish,wished,open}){return <article className="card"><button className="wish" onClick={()=>toggleWish(p)}>{wished?<Heart fill="currentColor"/>:<Heart/>}</button><button className="cardimage" onClick={open}><ProductArt p={p}/></button><div className="cardbody"><span className="regiontag">{p.region}</span><button className="cardtitle" onClick={open}>{p.name}</button><div className="rating"><Star fill="currentColor"/> {p.rating} <span>·</span> <small>{p.category}</small></div><div className="price">{money(p.price)} <small>incl. taxes*</small></div><button className="add" onClick={()=>add(p)}>Add to cart</button></div></article>}
function Shop({products,region,setRegion,category,setCategory,sort,setSort,add,toggleWish,wishlist,open}){return <main className="page"><div className="pagehead"><span className="eyebrow">THE COLLECTION</span><h1>Shop India</h1><p>Browse regional finds, artisan-inspired goods and thoughtful gifts.</p></div><div className="filters"><select value={region} onChange={e=>setRegion(e.target.value)}><option>All</option>{regions.map(r=><option key={r}>{r}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="priceLow">Price: low to high</option><option value="priceHigh">Price: high to low</option></select><span className="results">{products.length} products</span></div><div className="grid">{products.map(p=><Card key={p.sku} p={p} add={add} toggleWish={toggleWish} wished={wishlist.includes(p.sku)} open={()=>open(p)}/>)}</div>{!products.length&&<div className="empty">No products match these filters.</div>}</main>}
function Collection({title,intro,products,add,toggleWish,wishlist,open,empty}){return <main className="page"><div className="pagehead"><span className="eyebrow">FREEMART</span><h1>{title}</h1><p>{intro}</p></div>{products.length?<div className="grid">{products.map(p=><Card key={p.sku} p={p} add={add} toggleWish={toggleWish} wished={wishlist.includes(p.sku)} open={()=>open(p)}/>)}</div>:<div className="empty">{empty}</div>}</main>}
function Regions({nav,setRegion}){return <main className="page"><div className="pagehead"><span className="eyebrow">SHOP BY PLACE</span><h1>India, region by region.</h1><p>Choose a region and explore the products, materials and stories associated with it.</p></div><div className="regiongrid">{regions.map((r,i)=><button key={r} onClick={()=>{setRegion(r);nav('shop')}}><span>{String(i+1).padStart(2,'0')}</span><b>{r}</b><ChevronRight/></button>)}</div></main>}
function Categories({setCategory,nav}){return <main className="page"><div className="pagehead"><span className="eyebrow">SHOP BY CATEGORY</span><h1>Find your kind of beautiful.</h1><p>From everyday utility to festive gifting.</p></div><div className="categorygrid">{categories.map((c,i)=><button key={c} onClick={()=>{setCategory(c);nav('shop')}}><div className="catnum">0{i+1}</div><h2>{c}</h2><span>Explore collection <ChevronRight/></span></button>)}</div></main>}
function ProductDetail({p,add,toggleWish,wished,nav}){return <main className="page detail"><div className="detailgrid"><div><ProductArt p={p}/></div><div className="detailcopy"><span className="regiontag">{p.region} · {p.category}</span><h1>{p.name}</h1><div className="rating"><Star fill="currentColor"/> {p.rating} · FreeMart curated</div><div className="detailprice">{money(p.price)}</div><p>{p.desc}</p><div className="bullet"><b>Product details</b><span>{p.details}</span><span>SKU: {p.sku}</span><span>{p.stock}</span></div><div className="detailactions"><button className="primary" onClick={()=>add(p)}>Add to cart</button><button className="secondary" onClick={()=>toggleWish(p)}>{wished?'♥ Saved':'♡ Wishlist'}</button></div><button className="back" onClick={()=>nav('shop')}>← Back to shop</button></div></div><div className="storybox"><h2>The regional connection</h2><p>This product is presented as part of FreeMart’s regional discovery catalogue. Before launch, supplier/artisan attribution, GI/ODOP references, certifications and exact material claims should be verified against the final source documentation.</p></div></main>}
function Cart({cart,setCart,subtotal,nav}){return <main className="page cartpage"><div className="pagehead"><span className="eyebrow">YOUR BAG</span><h1>Shopping cart</h1></div>{cart.length?<div className="cartgrid"><div>{cart.map(x=><div className="cartrow" key={x.sku}><ProductArt p={x}/><div><h3>{x.name}</h3><small>{x.region} · {x.sku}</small><div className="qty"><button onClick={()=>setCart(c=>c.map(a=>a.sku===x.sku?{...a,qty:Math.max(1,a.qty-1)}:a))}><Minus/></button><b>{x.qty}</b><button onClick={()=>setCart(c=>c.map(a=>a.sku===x.sku?{...a,qty:a.qty+1}:a))}><Plus/></button></div></div><strong>{money(x.price*x.qty)}</strong><button className="remove" onClick={()=>setCart(c=>c.filter(a=>a.sku!==x.sku))}>Remove</button></div>)}</div><aside className="summary"><h2>Order summary</h2><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Shipping</span><b>{subtotal>=1999?'FREE':'Calculated at checkout'}</b></div><hr/><div className="total"><span>Total</span><b>{money(subtotal)}</b></div><button className="primary full" onClick={()=>nav('checkout')}>Proceed to checkout</button><small>Secure checkout · Payment gateway connected during launch setup</small></aside></div>:<div className="empty"><ShoppingBag/><h2>Your cart is empty</h2><button className="primary" onClick={()=>nav('shop')}>Start shopping</button></div>}</main>}
function Checkout({cart,subtotal,setOrders,nav,notify}){const [done,setDone]=useState(false);const [form,setForm]=useState({name:'',email:'',phone:'',address:'',city:'',state:'',pin:''});const change=e=>setForm({...form,[e.target.name]:e.target.value}); if(done)return <main className="page success"><div className="successmark">✓</div><span className="eyebrow">ORDER CONFIRMED</span><h1>Thank you, {form.name||'there'}.</h1><p>Your demo order has been created locally. Razorpay and production order verification should be connected on the hosted backend before launch.</p><button className="primary" onClick={()=>nav('account')}>View my orders</button></main>; return <main className="page"><div className="pagehead"><span className="eyebrow">CHECKOUT</span><h1>Complete your order</h1></div><div className="checkoutgrid"><form className="checkoutform" onSubmit={e=>{e.preventDefault();const id='FM'+Date.now().toString().slice(-7);setOrders(o=>[{id,date:new Date().toLocaleDateString('en-IN'),total:subtotal,status:'Order placed',items:cart.length},...o]);setDone(true);notify('Order placed')}}><h2>Delivery details</h2><div className="twocol"><input required name="name" value={form.name} onChange={change} placeholder="Full name"/><input required name="email" type="email" value={form.email} onChange={change} placeholder="Email"/></div><div className="twocol"><input required name="phone" value={form.phone} onChange={change} placeholder="Phone number"/><input required name="pin" value={form.pin} onChange={change} placeholder="PIN code"/></div><input required name="address" value={form.address} onChange={change} placeholder="Address"/><div className="twocol"><input required name="city" value={form.city} onChange={change} placeholder="City"/><input required name="state" value={form.state} onChange={change} placeholder="State"/></div><div className="paymentnote"><ShieldCheck/><div><b>Payment gateway ready</b><p>Connect Razorpay on the production backend. Never place secret payment keys in frontend code.</p></div></div><button className="primary full">Place order</button></form><aside className="summary"><h2>Your order</h2>{cart.map(x=><div className="mini" key={x.sku}><span>{x.name} × {x.qty}</span><b>{money(x.price*x.qty)}</b></div>)}<hr/><div className="total"><span>Total</span><b>{money(subtotal)}</b></div></aside></div></main>}
function Account({orders,nav}){return <main className="page"><div className="pagehead"><span className="eyebrow">MY ACCOUNT</span><h1>Welcome to FreeMart.</h1><p>Order history and customer account space.</p></div><div className="accountcard"><User/><h2>Customer account</h2><p>Production login, saved addresses, wishlist sync and order tracking can be connected to the backend after hosting.</p></div><h2 className="subhead">Orders</h2>{orders.length?<div className="orders">{orders.map(o=><div key={o.id}><Package/><div><b>{o.id}</b><small>{o.date} · {o.items} item(s)</small></div><strong>{money(o.total)}</strong><span>{o.status}</span></div>)}</div>:<div className="empty small">No orders yet. <button className="textbtn" onClick={()=>nav('shop')}>Shop now</button></div>}</main>}
function About({nav}){return <main className="page about"><div className="pagehead"><span className="eyebrow">ABOUT FREEMART</span><h1>India is not one story.<br/><i>It is thousands.</i></h1><p>FreeMart is a discovery-first marketplace concept built around regional identity, craftsmanship and better product context.</p></div><div className="aboutgrid"><div className="aboutvisual">FM</div><div><h2>Our idea</h2><p>Instead of making regional products feel anonymous, FreeMart starts with place. A customer can discover a product through Rajasthan, Gujarat, Assam, Odisha and more — then learn what makes that place special.</p><h2>GI & ODOP</h2><p>Where applicable, the live store should display verified Geographical Indication and One District One Product information with source references. This demo deliberately avoids claiming certification that has not been verified.</p><button className="primary" onClick={()=>nav('shop')}>Explore products</button></div></div></main>}
function InfoPage({title,text}){return <main className="page infopage"><span className="eyebrow">FREEMART</span><h1>{title}</h1><p>{text}</p><div className="legalbox"><h3>Launch note</h3><p>Replace this placeholder with your final business/legal text before accepting real customer orders. Shipping timelines, returns, privacy practices, GST details and payment terms should match the actual operating business.</p></div></main>}
function Admin({products,orders}){return <main className="page"><div className="pagehead"><span className="eyebrow">ADMIN PANEL</span><h1>FreeMart operations</h1><p>Starter dashboard for products, orders and inventory.</p></div><div className="adminstats"><div><Package/><b>{products.length}</b><span>Products</span></div><div><ShoppingBag/><b>{orders.length}</b><span>Orders</span></div><div><ShieldCheck/><b>10</b><span>Regions</span></div><div><Star/><b>6</b><span>Categories</span></div></div><div className="adminbox"><h2>Management modules</h2><div className="modules">{['Products','Categories','Regions','Orders','Customers','Inventory','Coupons','Sales'].map(x=><div key={x}><b>{x}</b><span>Ready for backend connection</span></div>)}</div></div></main>}

createRoot(document.getElementById('root')).render(<App/>);
